@startuml go-dsgn-pttrn-simple-factory

namespace simple-factory {

    class client {
        + createProduct(...) iAbstractProduct
    }

    object ProductA {

    }

    class concreteProductA << (S,Aquamarine) >> {
        - behaviourA string
        - featureA int

        + setBehaviour(behaviour string) 
        + getBehaviour() string
        + setFeature(feature int) 
        + getFeature() int

    }
    class concreteProductB << (S,Aquamarine) >> {
        - behaviourB string
        - featureB int

        + setBehaviour(behaviour string) 
        + getBehaviour() string
        + setFeature(feature int) 
        + getFeature() int

    }

    object ProductB {

    }

    interface iAbstractProduct  {
        + setBehaviour(behaviour string) 
        + getBehaviour() string
        + setFeature(feature int) 
        + getFeature() int

    }



}

"simple-factory.client" --> "simple-factory.iAbstractProduct"

"simple-factory.client" ..> "ProductA"
ProductA <.. "simple-factory.concreteProductA"
"simple-factory.client" ..> "ProductB"
ProductB <.. "simple-factory.concreteProductB"

"simple-factory.iAbstractProduct" <|.. "simple-factory.concreteProductA"
"simple-factory.iAbstractProduct" <|.. "simple-factory.concreteProductB"

@enduml
